name: Main

on:
  push:
    branches:
    - deploy

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Login
        run: echo $CR_PAT | docker login ghcr.io -u ${OWNER,,} --password-stdin
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
      - name: Publish
        run: |
          make publish
        env:
          OWNER: ${{ github.repository_owner }}
      - name: Logout
        run: docker logout
